// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfl9v4XRjXUuu9-2H4b1L_jMzYUCrvaGI',
    appId: '1:253387560569:web:6c65343e500bd00a9266a8',
    messagingSenderId: '253387560569',
    projectId: 'harita1-ba97d',
    authDomain: 'harita1-ba97d.firebaseapp.com',
    storageBucket: 'harita1-ba97d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASA2SKU1muIVv1SzaFidEXv-R6rHMKnCo',
    appId: '1:253387560569:android:bf0457a607bf87829266a8',
    messagingSenderId: '253387560569',
    projectId: 'harita1-ba97d',
    storageBucket: 'harita1-ba97d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgKFpCOPHQ5wB9DQgZdVnVYGjjDqxZzbY',
    appId: '1:253387560569:ios:3e38eb94c8e03a559266a8',
    messagingSenderId: '253387560569',
    projectId: 'harita1-ba97d',
    storageBucket: 'harita1-ba97d.appspot.com',
    iosBundleId: 'com.example.googleMapsOdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgKFpCOPHQ5wB9DQgZdVnVYGjjDqxZzbY',
    appId: '1:253387560569:ios:2b33cd61df9cd1159266a8',
    messagingSenderId: '253387560569',
    projectId: 'harita1-ba97d',
    storageBucket: 'harita1-ba97d.appspot.com',
    iosBundleId: 'com.example.googleMapsOdev.RunnerTests',
  );
}
